### ISSUE TITLE
Unable to build FreeRTOS posix example

### ISSUE THREAD

**Issue by sriharsha88** [igor-krechetov/hsmcpp#7] opened 2023-10-28 03:06 UTC
Hi @igor-krechetov,

I am trying to build hsmcpp library for Renesas Cortex M33 MCU. As a start I tried building the freertos posix port [example/08_freertos](https://github.com/igor-krechetov/hsmcpp/tree/main/examples/08_freertos). The build fails at linking stage. Its failing to link following libraries. 

- freertos_kernel
- freertos_kernel_port

Where can i find these libraries? They are not available in the FreeRTOS souce directory as well. I have attached the build log. Please have a look. 
[build-log.txt](https://github.com/igor-krechetov/hsmcpp/files/13194277/build-log.txt)

Regards,
Harsha

**Comment by sriharsha88** [comment] 2023-11-02 19:24
Hi @igor-krechetov,

I am able to port the FreeRTOS example to Renesas Cortex M33 MCU architecture. I am sharing my debugging experience here for anyone porting various FreeRTOS based MCUs.

Following FreeRTOS configurations are must for the [example/08_freertos](https://github.com/igor-krechetov/hsmcpp/tree/main/examples/08_freertos) switch example to be executed on Renesas MCU.

- INCLUDE_xTaskGetCurrentTaskHandle = 1
- configUSE_TASK_NOTIFICATIONS = 1
- configUSE_TIMERS = 1
- configUSE_MUTEXES = 1
- configSUPPORT_DYNAMIC_ALLOCATION = 1
- configMINIMAL_STACK_SIZE = 512

**Comment by sriharsha88** [comment] 2023-11-02 19:37
Hi @igor-krechetov,

Also found the following explicit type casting of timer interval parameter necessary for registerStateAction() to succeed.

`
(void)registerStateAction(SwitchHsmStates::Paused, hsmcpp::StateActionTrigger::ON_STATE_ENTRY, hsmcpp::StateAction::START_TIMER, static_cast<hsmcpp::TimerID_t>(SwitchHsmTimers::RESUME),  static_cast<int32_t>(2000),  true);
    (void)registerStateAction(SwitchHsmStates::Init, hsmcpp::StateActionTrigger::ON_STATE_EXIT, hsmcpp::StateAction::START_TIMER, static_cast<hsmcpp::TimerID_t>(SwitchHsmTimers::PAUSE), static_cast<int32_t>(5000),  false);
`
Without explicit type casting, registerStateAction() would fail with 'invalid arguments' error. The 'newAction.actionArgs[1].isNumeric()' condition evaluated to false in function HierarchicalStateMachine::Impl::registerStateAction() without type casting.

**Comment by igor-krechetov** [comment] 2023-11-08 18:08
Hi @sriharsha88 . 

Glad this worked out for you and also thank you for sharing solution here. Though I'm curious about the FreeRTOS configuration that you mentioned. All these flags were already defined in **FreeRTOSConfig.h** in the **08_freertos** example. And also available in the reference config in **include/hsmcpp/os/freertos/FreeRTOSConfig.h** . Have your tried them? I only tested the library with the POSIX simulation of the FreeRTOS so it's always helpfull to know which configurations should be used for specific MCUs.

> Hi @igor-krechetov,
> 
> I was able to port the FreeRTOS example to Renesas Cortex M33 MCU architecture. I am sharing my debugging experience here for anyone porting this library to various FreeRTOS based hardware platforms.
> 
> Following FreeRTOS configurations are must for the [example/08_freertos](https://github.com/igor-krechetov/hsmcpp/tree/main/examples/08_freertos) switch example to be executed on Renesas MCU.
> 
> * INCLUDE_xTaskGetCurrentTaskHandle = 1
> * configUSE_TASK_NOTIFICATIONS = 1
> * configUSE_TIMERS = 1
> * configUSE_MUTEXES = 1
> * configSUPPORT_DYNAMIC_ALLOCATION = 1
> * configMINIMAL_STACK_SIZE = 512


As for type casting issue, this looks like a problem with code generator. I remember fixing something similar before for FreeRTOS build. I'll double check and push a fix.

**Comment by igor-krechetov** [comment] 2024-01-14 16:07
Hi @sriharsha88 .

Just an update on the raised issues with FreeRTOS build before closing the ticket:

* The 08_freertos example was made to work with POSIX simulation of FreeRTOS.
  * Tested OS version: **FreeRTOS 202112.00** (**ad88de61d09759bd24dc3cf56bf2e2696ccd118f**, Fri Apr 8 23:44:17 2022)
  * To check for missing freertos_kernel_port library see if you have files in FreeRTOS/Source/portable/ThirdParty/GCC/Posix folder.
* Make sure to add FreeRTOS configurations as shown in the reference config: **include/hsmcpp/os/freertos/FreeRTOSConfig.h**
* Depending on the target architecture and compiler there might be an issue with int type (shouldn't be, but can't fix unless someone shares build environment where it's reproduced). As a workaround you can define timeout value in scxml with static_cast. Example: **start_timer(T1, static_cast<int32_t>(1000), true)**

**Closed by igor-krechetov** 2024-01-14 16:07 UTC
